# Generated by Django 5.1.4 on 2025-02-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_total_price_alter_product_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='unit_price',
            field=models.IntegerField(null=True),
        ),
    ]
